tap "facebook/fb"

mas "amphetamine", id: 937984704
mas "xcode", id: 497799835

cask "1password"
cask "codex"
#cask "cursor"
#cask "datagrip"
#cask "ghostty"
cask "google-chrome"
cask "google-drive"
cask "logitune"
cask "ngrok"
cask "nordvpn"
cask "raycast"
cask "slack"
cask "vlc"
cask "warp"
cask "wispr-flow"

brew "anomalyco/tap/opencode"
brew "az"
brew "caddy"
brew "cloc"
brew "ffmpeg"
brew "gh"
brew "git"
brew "idb-companion"
brew "imagemagick"
brew "libyaml"
brew "mise"
brew "mole"
brew "neovim"
brew "pipx"
brew "postgresql"
brew "redis"
brew "rtk"
brew "sqlite"
brew "terraform"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "watchman"
brew "wget"
