tap "facebook/fb"

mas "amphetamine", id: 937984704
mas "xcode", id: 497799835

cask "android-studio"
cask "bitwarden"
cask "codex"
#cask "datagrip"
cask "droid"
cask "fluidvoice"
cask "font-hack-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "google-drive"
cask "herdr"
cask "logitune"
cask "ngrok"
cask "nordvpn"
cask "pi-coding-agent"
#cask "raycast"
cask "slack"
cask "vlc"
cask "wispr-flow"
cask "zed"

brew "anomalyco/tap/opencode"
brew "awscli"
brew "az"
brew "caddy"
brew "cloc"
brew "ffmpeg"
brew "gh"
brew "git"
brew "idb-companion"
brew "imagemagick"
brew "libyaml"
brew "mise"
brew "maestro"
brew "mole"
brew "neovim"
brew "pipx"
brew "pnpm"
brew "postgresql"
brew "redis"
brew "rtk"
brew "stripe"
brew "sqlite"
brew "terraform"
brew "the_silver_searcher"
brew "tree"
brew "vips"
brew "watchman"
brew "wget"
brew "worktrunk"
