#theme = "catppuccin-mocha"
theme = "auto"
hunk_headers = false
wrap_lines = true
prompt_save_view_preferences = false
mode = "stacked"
agent_notes = true
transparent_background = true
watch = true
menu_bar = false
